ImagePreloader=function(){this.images=[];return this};ImagePreloader.prototype={images:null};Plane=function(){this.F=new Vector;return this};
Plane.prototype={s:0,t:0,u:0,L:0,F:null,reset:function(){this.s=this.t=this.u=this.L=0},Ua:function(){this.s*=-1;this.t*=-1;this.u*=-1;this.L*=-1;return this},sb:function(a,b,c){return this.s*a+this.t*b+this.u*c>0},wa:function(a){return this.sb(a.x,a.y,a.b)},face:function(a,b,c){if(this.s*a+this.t*b+this.u*c-this.L>0){this.s=-this.s;this.t=-this.t;this.u=-this.u;this.L=-this.L}return this},Da:function(a){this.bb(a.c[0],a.c[1],a.c[2]);return this},bb:function(a,b,c){var d=a.h;a=Vector.prototype.Lb(a.h,
b.h,c.h).normalize();this.s=a.x;this.t=a.y;this.u=a.b;this.L=this.s*d.x+this.t*d.y+this.u*d.b;return this},Cb:function(a){this.F.i(this.s,this.t,this.u);this.F=this.F.Ja(a)}};Vector=function(){this.x=this.y=this.b=0;return this};
Vector.prototype={x:0,y:0,b:0,i:function(a,b,c){this.x=a;this.y=b;this.b=c;return this},normalize:function(){var a=Math.sqrt(this.x*this.x+this.y*this.y+this.b*this.b);if(a===0)return this;a=1/a;this.x*=a;this.y*=a;this.b*=a;return this},Ua:function(){this.x=-this.x;this.y=-this.y;this.b=-this.b;return this},D:function(){var a=new Vector;a.i(this.x,this.y,this.b);return a},transform:function(a){var b=this.x*a.a[0]+this.y*a.a[1]+this.b*a.a[2]+a.a[3],c=this.x*a.a[4]+this.y*a.a[5]+this.b*a.a[6]+a.a[7];
a=this.x*a.a[8]+this.y*a.a[9]+this.b*a.a[10]+a.a[11];return(new Vector).i(b,c,a)},Ja:function(a){var b=this.x*a.a[0]+this.y*a.a[1]+this.b*a.a[2],c=this.x*a.a[4]+this.y*a.a[5]+this.b*a.a[6];a=this.x*a.a[8]+this.y*a.a[9]+this.b*a.a[10];return(new Vector).i(b,c,a)},Lb:function(a,b,c){return Vector.prototype.Ia(Vector.prototype.ba(c,a),Vector.prototype.ba(b,a))},Ia:function(a,b){var c=a.x,d=a.y,e=a.b,f=b.x,g=b.y,i=b.b,q=new Vector;q.i(d*i-e*g,e*f-c*i,c*g-f*d);return q},Kb:function(a,b){var c=new Vector;
c.i(a.x+b.x,a.y+b.y,a.b+b.b);return c},ba:function(a,b){var c=new Vector;c.i(a.x-b.x,a.y-b.y,a.b-b.b);return c}};Matrix=function(){this.a=[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];return this};
Matrix.prototype={a:null,Eb:function(a,b,c){this.rb();this.a[0]=a.x;this.a[1]=a.y;this.a[2]=a.b;this.a[4]=b.x;this.a[5]=b.y;this.a[6]=b.b;this.a[8]=c.x;this.a[9]=c.y;this.a[10]=c.b;return this},rb:function(){for(var a=0;a<4;a++)for(var b=0;b<4;b++)this.a[4*a+b]=a==b?1:0;return this},D:function(){for(var a=new Matrix,b=0;b<16;b++)a.a[b]=this.a[b];return a},Aa:function(a){var b=this.D();this.a[0]=a.a[0]*b.a[0]+a.a[1]*b.a[4]+a.a[2]*b.a[8];this.a[1]=a.a[0]*b.a[1]+a.a[1]*b.a[5]+a.a[2]*b.a[9];this.a[2]=
a.a[0]*b.a[2]+a.a[1]*b.a[6]+a.a[2]*b.a[10];this.a[3]=a.a[0]*b.a[3]+a.a[1]*b.a[7]+a.a[2]*b.a[11]+a.a[3];this.a[4]=a.a[4]*b.a[0]+a.a[5]*b.a[4]+a.a[6]*b.a[8];this.a[5]=a.a[4]*b.a[1]+a.a[5]*b.a[5]+a.a[6]*b.a[9];this.a[6]=a.a[4]*b.a[2]+a.a[5]*b.a[6]+a.a[6]*b.a[10];this.a[7]=a.a[4]*b.a[3]+a.a[5]*b.a[7]+a.a[6]*b.a[11]+a.a[7];this.a[8]=a.a[8]*b.a[0]+a.a[9]*b.a[4]+a.a[10]*b.a[8];this.a[9]=a.a[8]*b.a[1]+a.a[9]*b.a[5]+a.a[10]*b.a[9];this.a[10]=a.a[8]*b.a[2]+a.a[9]*b.a[6]+a.a[10]*b.a[10];this.a[11]=a.a[8]*b.a[3]+
a.a[9]*b.a[7]+a.a[10]*b.a[11]+a.a[11]},moveTo:function(a){return this.Xa(a.x,a.y,a.b)},Xa:function(a,b,c){this.a[3]=a;this.a[7]=b;this.a[11]=c;return this},Gb:function(a){for(var b=-a.a[3],c=-a.a[7],d=-a.a[11],e=0;e<3;e++)for(var f=0;f<3;f++)this.a[e+f*4]=a.a[f+e*4];this.a[3]=b*this.a[0]+c*this.a[1]+d*this.a[2];this.a[7]=b*this.a[4]+c*this.a[5]+d*this.a[6];this.a[11]=b*this.a[8]+c*this.a[9]+d*this.a[10]},Ca:function(a,b,c){var d=Math.sin(a),e=Math.sin(b),f=Math.sin(c);a=Math.cos(a);b=Math.cos(b);
c=Math.cos(c);this.a[0]=b*a;this.a[1]=-b*d;this.a[2]=e;this.a[3]=0;this.a[4]=f*e*a+d*c;this.a[5]=c*a-f*e*d;this.a[6]=-f*b;this.a[7]=0;this.a[8]=f*d-c*e*a;this.a[9]=c*e*d+f*a;this.a[10]=c*b;this.a[11]=0;this.a[12]=0;this.a[13]=0;this.a[14]=0;this.a[15]=1;return this},copy:function(a){for(var b=15;b>=0;b--)this.a[b]=a.a[b];return this}};Particle=function(){this.position=new Vector;return this};
Particle.prototype={position:null,l:0,xa:0,aa:0,enabled:false,X:0,pa:0,La:1,oa:3E3,fb:4E3,Ab:0,k:0,r:0,$:0,x:0,y:0,b:0,type:2,sa:0,ka:null,color:"#ff",m:0,n:0,na:0,A:function(a,b,c){this.position.i(a,b,c)},cb:function(a){this.enabled=true;switch(this.type){case 0:this.$=140+15*Math.random();this.k=2*Math.PI*Math.random();this.r=Math.PI/3+Math.PI/16;break;case 1:this.$=140+15*Math.random();this.k=Math.PI/8*Math.random()+this.sa;Particle.prototype.sa+=Math.PI/180;this.r=Math.PI/3+Math.PI/16;break;case 2:this.$=
140+15*Math.random();this.k=Math.PI/4*Math.random();this.r=Math.PI/3+Math.PI/16;var b=Math.random();if(b>0.66)this.k+=120*Math.PI/180;else if(b>0.33)this.k+=240*Math.PI/180;this.k+=this.sa;break}b=this.$*Math.cos(this.r);this.x=b*Math.cos(this.k);this.b=b*Math.sin(this.k);this.y=this.$*Math.sin(this.r);this.Ab=Math.floor(200*Math.random());this.X=a;this.l=0;this.xa=this.fb;this.position.i(0,0,0)},Mb:function(a,b){if(this.aa==this.pa){if(this.l==0){this.l=a-this.X;return true}this.position.x=this.x*
this.l/100;this.position.b=this.b*this.l/100;this.position.y=this.y*this.l/100-5*this.l*this.l/1E4;this.l=a-this.X;if(this.l>=this.oa||this.position.y<0){this.aa=this.La;this.X=a;this.l=0;this.position.y=0}}else if(this.aa==this.La){if(this.l>this.xa-this.oa){this.aa=this.pa;if(b)this.cb(a);else this.enabled=false;this.l=a}this.l=a-this.X}return false},p:function(a,b){var c=this.position.transform(b),d=c.x,e=c.y;c=a.ga/c.b;this.m=a.width/2+d*c;this.n=a.height/2-e*c;this.na=Math.abs(a.width/2+(d+24)*
c-this.m);this.m-=this.na/2;this.n-=this.na/2;a.j.beginPath();a.j.arc(this.m,this.n,this.na,0,2*Math.PI,false);a.j.fillStyle=this.color;if(this.aa!=this.pa){alpha=this.l/(this.xa-this.oa);if(alpha>1)alpha=1;a.j.globalAlpha=1-alpha}else a.j.globalAlpha=1;a.j.fill();a.j.globalAlpha=1}};ParticleSystem=function(){this.ob=["#00ff00","#00ff7f","#007fff","#007f3f","#007f3f"];return this};
ParticleSystem.prototype={Q:null,Ya:null,o:0,la:0,enabled:false,wb:true,k:0,U:null,ob:null,Ga:function(a,b){if(!this.enabled)return this;this.Ya.Ca(0,this.k,0);this.U=this.Ya.D();this.U.a[3]-=b.v.S.x;this.U.a[7]-=b.v.S.y;this.U.a[11]-=b.v.S.b;this.U.Aa(b.v.q);if(this.o<this.la)this.o<this.la&&this.Q[this.o++].cb(b.currentTime);else if(this.o>this.la)for(;this.o>this.la;){if(this.o<this.Q.length&&this.o>=0)this.Q[this.o].enabled=false;this.o--}return this},p:function(a){for(var b=0,c=0;c<this.o;c++)if(this.Q[c].enabled){this.Q[c].p(a,
this.U);this.Q[c].Mb(a.currentTime,this.wb);b++}if(this.o>0&&b==0)this.enabled=false}};Scene=function(){this.Ra=90;this.v=new Camera;this.v.Fa((new Vector).i(0,0,-700),(new Vector).i(0,0,0));this.ma=[];this.R=new RenderPipeline;return this};
Scene.prototype={width:0,height:0,ga:0,Ra:90,j:null,v:null,currentTime:0,ma:null,Pa:0,R:null,ja:0,Z:0,Qa:0,Nb:0,Sa:0,background:"#ffffff",ya:null,Va:null,Hb:function(a,b){this.width=a;this.height=b;this.ga=a/Math.tan(this.Ra/2);this.ya=(new Vector).i(-1,0,0);return this},Ib:function(a){this.j=a;return this},ia:function(){return this.width},ha:function(){return this.height},nb:function(){this.ja++;this.Y=(new Date).getTime();if(this.Y-this.Z>=500){if(this.Y-this.Z<2E3)this.Nb+=this.Y-this.Z;this.Qa=
this.ja/((this.Y-this.Z)/1E3);this.ja=0;this.Z=this.Y}var a=Math.floor(this.Qa*100);if(this.ja==0)this.Sa=a/100},p:function(){this.j.save();this.j.fillStyle=this.background;this.j.clearRect(0,0,this.width,this.height);this.R.reset();this.Va=this.ya.D().normalize();for(var a=0;a<this.ma.length;a++)this.ma[a].Ga(this.Pa,this,this.v);this.R.p(this);this.nb();this.j.strokeStyle="#0";this.j.strokeText("Fps: "+this.Sa,10,30);this.j.strokeText("Faces: "+(this.R.ca.g.length+this.R.P.g.length),10,20);this.j.restore();
this.Pa++},ib:function(a){this.ma.push(a)}};Camera=function(){this.q=new Matrix;this.S=new Vector;this.Wa=new Vector;this.forward=new Vector;return this};Camera.prototype={q:null,S:null,Wa:null,forward:null,Ka:0,k:0,r:0,ga:0,Fa:function(a,b){this.S=a.D();this.Wa=b.D();this.forward=Vector.prototype.ba(a,b);var c=(new Vector).i(0,-1,0),d=Vector.prototype.Ia(c,this.forward);c=Vector.prototype.Ia(this.forward,d);this.forward.normalize();c.normalize();d.normalize();this.q=(new Matrix).Eb(d,c,this.forward)}};
Vertex=function(){this.h=new Vector;this.T=new Vector;this.ub=new Vector;this.Bb=new Vector;this.Na=[];return this};Vertex.prototype={h:null,ub:null,T:null,Bb:null,m:0,n:0,Na:null,Za:-1,ra:function(a){this.Na.push(a);return this},Ba:function(a,b,c){if(a==this.Za)return this;this.T=this.h.transform(c);this.Za=a;b/=this.T.b;this.m=this.T.x*b+h.width/2;this.n=-this.T.y*b+h.height/2;return this}};
Model=function(){this.position=new Vector;this.V=new Vector;this.c=[];this.g=[];this.w=new Matrix;this.q=new Matrix;this.za=new Matrix;this.tb=true;return this};
Model.prototype={position:null,V:null,c:null,g:null,w:null,q:null,za:null,tb:false,k:0,r:0,Ka:0,mb:0,I:0,da:0,J:0,ea:0,K:0,fa:0,W:null,N:null,Ta:1,B:2,lb:function(a){this.c.push(a);return this},Ga:function(a,b,c){this.w.Ca(this.Ka,this.k,this.r);this.V=this.position.D();if(this.W!=null){this.V=Vector.prototype.Kb(this.W.V,this.position.Ja(this.W.w));if(this.Ta==this.B){this.w.Aa(this.W.w);this.w.Xa(0,0,0)}}var d=Vector.prototype.ba(this.V,c.S);this.za.Gb(this.w);var e=d.transform(this.za);this.q.copy(this.w);
this.q.moveTo(d.Ua());this.q.Aa(c.q);d=b.Va;for(var f=this.g.length-1;f>=0;f--)if(this.g[f].pb(e))if(this.g[f].Ba(a,b.ga,this.q)){this.g[f].O=-(this.g[f].z.F.x*d.x+this.g[f].z.F.y*d.y+this.g[f].z.F.b*d.b);b.R.jb(this.g[f])}if(null!=this.N)for(f=0;f<this.N.length;f++)this.N[f].Ga(a,b,c)},create:function(a,b){for(var c=0;c<a.length;c++){var d=new Vertex;d.h.i(a[c].x,a[c].y,a[c].b);this.lb(d)}for(c=0;c<b.length;c++)this.g.push((new Polygon).Jb(this.c[b[c].d],this.c[b[c].e],this.c[b[c].f]));this.vb();
return this},qb:function(){var a,b,c,d,e,f;f=e=d=c=b=a=0;for(var g=this.c.length-1;g>=0;g--){var i=this.c[g].h;if(i.x<this.c[a].h.x)a=g;if(i.x>this.c[b].h.x)b=g;if(i.y<this.c[c].h.y)c=g;if(i.y>this.c[d].h.y)d=g;if(i.b<this.c[e].h.b)e=g;if(i.b>this.c[f].h.b)f=g}this.I=this.c[a].h.x;this.da=this.c[b].h.x;this.J=this.c[c].h.y;this.ea=this.c[d].h.y;this.K=this.c[e].h.b;this.fa=this.c[f].h.b;a=0;if(Math.abs(this.I)>a)a=Math.abs(this.I);if(Math.abs(this.J)>a)a=Math.abs(this.J);if(Math.abs(this.K)>a)a=Math.abs(this.K);
if(Math.abs(this.da)>a)a=Math.abs(this.da);if(Math.abs(this.ea)>a)a=Math.abs(this.ea);if(Math.abs(this.fa)>a)a=Math.abs(this.fa);this.mb=a},vb:function(){this.qb();var a;for(a=this.c.length-1;a>=0;a--){this.c[a].h.x=this.c[a].h.x-this.I-(this.da-this.I)/2;this.c[a].h.y=this.c[a].h.y-this.J-(this.ea-this.J)/2;this.c[a].h.b=this.c[a].h.b-this.K-(this.fa-this.K)/2}for(a=0;a<this.g.length;a++)this.g[a].Da();this.A(this.position.x-this.I-(this.da-this.I)/2,this.position.y-this.J-(this.ea-this.J)/2,this.position.b-
this.K-(this.fa-this.K)/2)},A:function(a,b,c){this.position.i(a,b,c)},M:function(a,b){if(null==this.N)this.N=[];this.N.push(a);a.Fb(this,b)},Fb:function(a,b){this.W=a;this.Ta=b},Ea:function(a,b,c,d,e){for(var f=0;f<this.g.length;f++)this.g[f].Ea(a,b,c,d,e)}};Polygon=function(){this.c=[];this.z=new Plane;this.H=[0,0,0,0,0,0,0,0];this.style=0;return this};
Polygon.prototype={c:null,z:null,O:0,C:0,G:null,H:null,va:255,ua:0,ta:127,Oa:255,style:0,gb:1,qa:0,hb:2,Ma:4,Jb:function(a,b,c){this.c.push(a);this.c.push(b);this.c.push(c);a.ra(this);b.ra(this);c.ra(this);this.Da();return this},face:function(a,b,c){this.z.face(a,b,c);return this},wa:function(a){return this.z.wa(a)},pb:function(a){return this.wa(Vector.prototype.ba(this.c[0].h,a))},Da:function(){this.z.bb(this.c[0],this.c[1],this.c[2]);return this},Db:function(){for(var a=0,b=this.c.length-1;b>=0;b--)a+=
this.c[b].T.b;a/=this.c.length;this.C=a},Ba:function(a,b,c){for(var d=true,e=this.c.length-1;e>=0;e--){this.c[e].Ba(a,b,c);if(this.c[e].Ob<0.5)d=false}this.z.Cb(c);this.Db();return d},p:function(a){switch(this.style){case this.hb:this.zb(a);break;case this.qa:case this.Ma:this.xb(a);break;case this.gb:default:this.yb(a)}},yb:function(a){var b=this.c[0].m,c=this.c[0].n,d=this.c[1].m,e=this.c[1].n,f=this.c[2].m,g=this.c[2].n;a.beginPath();a.moveTo(b,c);a.lineTo(d,e);a.lineTo(f,g);a.lineTo(b,c);a.strokeStyle=
"#0";a.stroke()},xb:function(a){a.beginPath();a.moveTo(this.c[0].m,this.c[0].n);a.lineTo(this.c[1].m,this.c[1].n);a.lineTo(this.c[2].m,this.c[2].n);a.closePath();if(this.O<0)this.O=0;var b=Math.floor(this.O*this.va),c=Math.floor(this.O*this.ua),d=Math.floor(this.O*this.ta),e=this.color;if(this.style==this.Ma)e="rgb("+this.va+","+this.ua+","+this.ta+")";else if(this.style==this.qa)e="rgb("+b+","+c+","+d+")";a.fillStyle=e;a.fill();a.strokeStyle=e;a.stroke()},zb:function(a){var b=this.c[0].m,
c=this.c[0].n,d=this.c[1].m,e=this.c[1].n,f=this.c[2].m,g=this.c[2].n;a.save();a.beginPath();a.moveTo(b,c);a.lineTo(d,e);a.lineTo(f,g);a.lineTo(b,c);a.clip();a.stroke();var i=this.H[0]*this.G.ia(),q=this.H[1]*this.G.ha(),k=this.H[2]*this.G.ia(),l=this.H[3]*this.G.ha(),m=this.H[4]*this.G.ia(),n=this.H[5]*this.G.ha(),r=i*(n-l)-k*n+m*l+(k-m)*q;if(r!=0){a.setTransform(-(q*(f-d)-l*f+n*d+(l-n)*b)/r,(l*g+q*(e-g)-n*e+(n-l)*c)/r,(i*(f-d)-k*f+m*d+(k-m)*b)/r,-(k*g+i*(e-g)-m*e+(m-k)*c)/r,(i*(n*d-l*f)+q*(k*f-
m*d)+(m*l-k*n)*b)/r,(i*(n*e-l*g)+q*(k*g-m*e)+(m*l-k*n)*c)/r);a.drawImage(this.G.ka,0,0)}a.restore()},Ea:function(a,b,c,d,e){this.va=a;this.ua=b;this.ta=c;this.Oa=d;this.style=e}};RenderPipeline=function(){this.P=new PolygonStack;this.ca=new PolygonStack;return this};RenderPipeline.prototype={P:[],ca:[],$a:null,jb:function(a){this.P.kb(a)},reset:function(){this.P.reset();this.ca.reset()},p:function(a){this.P.db();this.P.p(a.j,this.$a);this.ca.db();this.ca.p(a.j,this.$a)}};
PolygonStack=function(){this.g=[];return this};
PolygonStack.prototype={g:null,kb:function(a){this.g.push(a)},reset:function(){this.g=[]},db:function(){this.g.length!=0&&this.Ha(0,this.g.length-1)},eb:function(a,b){var c,d,e;c=a;d=b;e=this.g[a+b>>1].C;do{for(;this.g[c].C>e;)++c;for(;e>this.g[d].C;)--d;if(c<=d){var f=this.g[c];this.g[c]=this.g[d];this.g[d]=f;++c;--d}}while(c<=d);a<d&&this.eb(a,d);c<b&&this.eb(c,b)},Ha:function(a,b){var c,d,e;c=a;d=b;e=this.g[a+b>>1].C;do{for(;this.g[c].C<e;)++c;for(;e<this.g[d].C;)--d;if(c<=d){var f=this.g[c];this.g[c]=
this.g[d];this.g[d]=f;++c;--d}}while(c<=d);a<d&&this.Ha(a,d);c<b&&this.Ha(c,b)},p:function(a){for(var b=this.g.length-1;b>=0;b--)this.g[b].p(a)}};Texture=function(){return this};Texture.prototype={ka:null,ia:function(){return this.ka.width-1},ha:function(){return this.ka.height-1}};Texturizer=function(){return this};Texturizer.prototype={};function j(){return(new Model).create([{x:-43.428,y:43.428,b:50},{x:43.428,y:43.428,b:50},{x:-43.428,y:-43.428,b:50},{x:43.428,y:-43.428,b:50},{x:-43.428,y:50,b:43.428},{x:-50,y:43.428,b:43.428},{x:-50,y:-43.428,b:43.428},{x:-43.428,y:-50,b:43.428},{x:43.428,y:-50,b:43.428},{x:50,y:-43.428,b:43.428},{x:50,y:43.428,b:43.428},{x:43.428,y:50,b:43.428},{x:-43.428,y:50,b:-43.428},{x:-50,y:43.428,b:-43.428},{x:-50,y:-43.428,b:-43.428},{x:-43.428,y:-50,b:-43.428},{x:43.428,y:-50,b:-43.428},{x:50,y:-43.428,
b:-43.428},{x:50,y:43.428,b:-43.428},{x:43.428,y:50,b:-43.428},{x:43.428,y:-43.428,b:-50},{x:-43.428,y:-43.428,b:-50},{x:43.428,y:43.428,b:-50},{x:-43.428,y:43.428,b:-50}],[{d:0,e:2,f:3},{d:0,e:3,f:1},{d:0,e:4,f:5},{d:0,e:5,f:6},{d:0,e:6,f:2},{d:2,e:6,f:7},{d:2,e:7,f:8},{d:2,e:8,f:3},{d:3,e:8,f:9},{d:3,e:9,f:10},{d:3,e:10,f:1},{d:1,e:10,f:11},{d:1,e:11,f:4},{d:1,e:4,f:0},{d:4,e:12,f:13},{d:4,e:13,f:5},{d:5,e:13,f:14},{d:5,e:14,f:6},{d:6,e:14,f:15},{d:6,e:15,f:7},{d:7,e:15,f:16},{d:7,e:16,f:8},{d:8,
e:16,f:17},{d:8,e:17,f:9},{d:9,e:17,f:18},{d:9,e:18,f:10},{d:10,e:18,f:19},{d:10,e:19,f:11},{d:11,e:19,f:12},{d:11,e:12,f:4},{d:12,e:23,f:13},{d:13,e:23,f:21},{d:13,e:21,f:14},{d:14,e:21,f:15},{d:15,e:21,f:20},{d:15,e:20,f:16},{d:16,e:20,f:17},{d:17,e:20,f:22},{d:17,e:22,f:18},{d:18,e:22,f:19},{d:19,e:22,f:23},{d:19,e:23,f:12},{d:22,e:20,f:21},{d:22,e:21,f:23}])};function o(){s=Math.PI/2*Math.cos(h.currentTime*9.0E-4);t.Ca(u,s,0);v=(new Vector).i(0,0,100).normalize();if(w)v=v.Ja(t);h.ya.i(-v.x,-v.y,-v.b);h.p();h.currentTime+=30;if(false==x){y[0].k=Math.PI*2*Math.cos(h.currentTime*1.0E-4);y[0].r=Math.PI*2*Math.sin(h.currentTime*2.0E-4)}else if(z)h.v.Fa((new Vector).i(0,0,D),(new Vector).i(0,0,0));else{y[0].k=E;y[0].r=F}for(var a=1;a<y.length;a++){var b=(a-1)/G;y[a].Ka=Math.PI/5*Math.cos(h.currentTime*9.0E-4)*(b%2==0?1:-1);y[a].k=Math.PI/7*Math.sin(h.currentTime*
6.0E-4)*(b%4==0?1:-1)}}
function H(){ctx=I.getContext("2d");h=(new Scene).Hb(600,400).Ib(ctx);h.v.Fa((new Vector).i(0,0,-1500),(new Vector).i(0,0,0));J=new Particle;J.color="#ff0000";t=new Matrix;y=[];var a,b=j();y.push(b);var c=b;for(a=0;a<G;a++){var d=j();y.push(d);c.M(d,Model.prototype.B);d.A(0,-150,0);c=d}c=b;for(a=0;a<G;a++){d=j();y.push(d);c.M(d,Model.prototype.B);d.A(0,150,0);c=d}c=b;for(a=0;a<G;a++){d=j();y.push(d);c.M(d,Model.prototype.B);d.A(150,0,0);c=d}c=b;for(a=0;a<G;a++){d=j();y.push(d);c.M(d,Model.prototype.B);
d.A(-150,0,0);c=d}c=b;for(a=0;a<G;a++){d=j();y.push(d);c.M(d,Model.prototype.B);d.A(0,0,150);c=d}c=b;for(a=0;a<G;a++){d=j();y.push(d);c.M(d,Model.prototype.B);d.A(0,0,-150);c=d}h.ib(b)}var I=null,h=null,y=null,G=5,v,t,u=0,s=0,J=null,w=true,D=-1500,x=false,K=-1,L=-1,z=false,E=0,F=0;
window.addEventListener("load",function(a){I=document.getElementById("screen");document.getElementById("color").addEventListener("change",function(){for(var b=Math.floor(document.getElementById("color").style.backgroundColor.split("(")[1].split(")")[0].split(",")[0]),c=Math.floor(document.getElementById("color").style.backgroundColor.split("(")[1].split(")")[0].split(",")[1]),d=Math.floor(document.getElementById("color").style.backgroundColor.split("(")[1].split(")")[0].split(",")[2]),e=0;e<y.length;e++)y[e].Ea(b,c,d,255,Polygon.prototype.qa)},false);document.getElementById("light").addEventListener("change",function(){w=!w},false);I.onmouseover=
function(b){if(!b)b=window.event;if(false==z){x=true;K=b.x;L=b.y}};I.onmouseout=function(){if(false==z){x=false;L=K=-1}};I.onmousedown=function(){z=true};I.onmouseup=function(){z=false};I.onmousemove=function(b){if(!b)b=window.event;if(x){if(z){D+=b.y-L;if(D>-1000)D=-1000;if(D<-2000)D=-2000}else{E+=(b.x-K)/500*2*Math.PI;F+=(b.y-L)/500*2*Math.PI}K=b.x;L=b.y}};I.width=600;I.height=400;H(a);setInterval(o,30)}(null),false);
